{
 "title": "todis-exporter",
 "description": "todis Metrics Monitor",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(todis_uptime_in_seconds{},instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,2m,5m,15m,30m,1h,3h,6h,12h,24h,2d,7d"
   },
   {
    "name": "data_type",
    "query": "strings,hashes,lists,sets,zsets"
   },
   { "name": "column_family", "query": "default,data_cf,score_cf" }
  ]
 },
 "panels": [
  { "title": "todis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(todis_memory_used_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(todis_cpu_sys_seconds_total{instance=\"$instance\"}[$interval])+rate(todis_cpu_user_seconds_total{instance=\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Disk Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(todis_used_disk_size{instance=\"$instance\"})/sum(todis_disk_capacity_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(todis_db_size{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(todis_connected_clients{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(todis_uptime_in_seconds{instance=\"$instance\"})",
     "legendFormat": "tmp"
    }
   ]
  },
  {
   "title": "Estimate Keys",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "todis_DBStrings_keys{instance=\"$instance\"}+todis_DBHashes_keys{instance=\"$instance\"}+todis_DBLists_keys{instance=\"$instance\"}+todis_DBSets_keys{instance=\"$instance\"}+todis_DBZsets_keys{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "OPS by command",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(todis_all_command_count{instance=\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(todis_memory_used_bytes{instance=\"$instance\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(todis_cpu_sys_seconds_total{instance=\"$instance\"}[$interval]))+sum(rate(todis_cpu_user_seconds_total{instance=\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "use disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_used_disk_size{instance=\"$instance\"}",
     "legendFormat": "disk"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_db_size{instance=\"$instance\"}",
     "legendFormat": "db size"
    }
   ]
  },
  {
   "title": "estimate keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_DBStrings_keys{instance=\"$instance\"}",
     "legendFormat": "strings"
    },
    {
     "expr": "todis_DBHashes_keys{instance=\"$instance\"}",
     "legendFormat": "hashes"
    },
    {
     "expr": "todis_DBLists_keys{instance=\"$instance\"}",
     "legendFormat": "lists"
    },
    {
     "expr": "todis_DBSets_keys{instance=\"$instance\"}",
     "legendFormat": "sets"
    },
    {
     "expr": "todis_DBZsets_keys{instance=\"$instance\"}",
     "legendFormat": "zsets"
    }
   ]
  },
  {
   "title": "OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(todis_all_command_count{instance=\"$instance\"}[$interval])",
     "legendFormat": "ops"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(todis_connected_clients{instance=\"$instance\"})",
     "legendFormat": "Connected Clients"
    },
    {
     "expr": "sum(todis_monitor_clients{instance=\"$instance\"})",
     "legendFormat": "Monitor Clients"
    },
    {
     "expr": "sum(todis_connected_slaves{instance=\"$instance\"})",
     "legendFormat": "Slave Clients"
    }
   ]
  },
  {
   "title": "expiring key",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_db_keys_expiring{instance=\"$instance\"}",
     "legendFormat": "expiring"
    }
   ]
  },
  { "title": "RocksDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "${data_type}_all_mem_tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_${data_type}_all_mem_tables{instance=\"$instance\"}",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_snapshots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "targets": [
    { "expr": "todis_${data_type}_snapshots", "legendFormat": "${data_type}" }
   ]
  },
  {
   "title": "${data_type}_cur_mem_tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_${data_type}_cur_mem_tables{instance=\"$instance\"}",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_num_immutable_mem_table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "todis_${data_type}_num_immutable_mem_table",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_num_running_flushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "todis_${data_type}_num_running_flushes",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_compaction_pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "todis_${data_type}_compaction_pending",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_mem_table_flush_pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "todis_${data_type}_mem_table_flush_pending",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_num_running_compactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "expr": "todis_${data_type}_num_running_compactions",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_num_live_versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "todis_${data_type}_num_live_versions",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_current_super_version_number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_${data_type}_current_super_version_number",
     "legendFormat": "${data_type}"
    }
   ]
  },
  {
   "title": "${data_type}_num_background_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "todis_${data_type}_num_background_errors",
     "legendFormat": "${data_type}"
    }
   ]
  },
  { "title": "RocksDB Column Family", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "${data_type}_estimate_num_keys_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_${data_type}_estimate_num_keys_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  },
  {
   "title": "${data_type}_level0_slowdown_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "targets": [
    {
     "expr": "todis_${data_type}_level0_slowdown_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  },
  {
   "title": "${data_type}_estimate_table_readers_mem_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "todis_${data_type}_estimate_table_readers_mem_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  },
  {
   "title": "${data_type}_level0_numfiles_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "targets": [
    {
     "expr": "todis_${data_type}_level0_numfiles_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  },
  {
   "title": "${data_type}_slowdown_for_pending_compaction_bytes_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "todis_${data_type}_slowdown_for_pending_compaction_bytes_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  },
  {
   "title": "${data_type}_memtable_slowdown_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
   "targets": [
    {
     "expr": "todis_${data_type}_memtable_slowdown_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  },
  {
   "title": "${data_type}_stop_for_pending_compaction_bytes_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "todis_${data_type}_stop_for_pending_compaction_bytes_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  },
  {
   "title": "${data_type}_memtable_compaction_${column_family}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 63 },
   "targets": [
    {
     "expr": "todis_${data_type}_memtable_compaction_${column_family}",
     "legendFormat": "${column_family}"
    }
   ]
  }
 ]
}